text-summaNum-consolClick
AndreyIvchenko/LandingPage pull request #15
Opened 2021-11-12 09:51 UTC by AndreyIvchenko

Привет. 
Я себя чувствую как старый ржавый МАЗ, который потиху пытается трогаться с места. )

2021-11-12 14:41 UTC, kirillstarovoitov requested changes

2021-11-12 14:41 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +function showString() {
this func should receive a param. At this implementation no params. Fix it pls

2021-11-12 14:41 UTC, kirillstarovoitov commented on index.html
>      <div style="width: 100%; height: 200px;"></div>
Whi we are using inline styles and for what this div is here?

2021-11-12 14:41 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +function summaNum(n1, n2) {
pls write the result in a variable then console.log it

2021-11-12 14:41 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +document.getElementById('but1').addEventListener('click', butClick)
pls write document.getElementById('but1') in variable (then u can console this variable and investigate result). Then add eventListener

2021-11-12 14:41 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +function showString() {
why we are using function declaration in this case?

2021-11-19 11:21 UTC, kirillstarovoitov requested changes

2021-11-19 11:21 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +showCons(1)
Task is: 4. Написать 2 функции, первая принимает параметр в виде строки и выводит консоль лог эту строку при вызове.
The first function should receive a string (not another data type). In this case, you pass the number and then (inside a function) transform it to a string. It is the wrong solution. Let's improve this task. If param type is a string - then console log this string. In another case - console log text "Wrong data type". And pls renate param from blabla to something human understandable (eg string or param or argument)

2021-11-19 11:21 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +    return n1 + n2;
Improve this function. return sum if numbers only then both arguments are numbers. For another case - return null and console log text "one or both params, not numbers"

2021-11-19 11:21 UTC, kirillstarovoitov commented on scripts/landingPage.js
> +let bid1 = document.getElementById("but1")
It is work. But call variable smth like button or .. u know.. All developers should understand what contains this variable.

2021-11-19 11:21 UTC, kirillstarovoitov commented on index.html
> +    <div></div>
this div is empty... Just remove it pls)

2021-12-15 14:12 UTC, AndreyIvchenko commented
done

2021-12-15 14:14 UTC, merged